server:
  port: 9090
  servlet:
    context-path: /cookie
    jsp:
      init-parameters:
        development: true
spring:
  redis:
    host: 192.168.41.153
    port: 6999
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yes?characterEncoding=UTF-8
    username: root
    password: 123123
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:com/my/mapper/*.xml
  type-aliases-package: com.my.entity
logging:
  level:
    root: info
    com.my.dao: debug
    com.my.service: debug